on: [push, pull_request]

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: 'Install Go'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v5

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: 'Bundle Zip'
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main'
      env:
        MATRIX_OS: ${{ matrix.os }}
      run: ./ci/github-bundle.sh
      shell: bash

    - name: Upload Files (non-windows)
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main' && runner.os != 'Windows'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Uploading files to bucket"
        aws s3 sync ./upload s3://duckdb-featureserv --endpoint-url $AWS_ENDPOINT_URL

    - name: Upload Files (windows)
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main' && runner.os == 'Windows'
      run: |
        chcp 65001 #set code page to utf-8
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $env:GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $env:GITHUB_ENV
        echo "AWS_ENDPOINT_URL=${{ secrets.AWS_ENDPOINT_URL }}" >> $env:GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}" >> $env:GITHUB_ENV

        echo "Uploading files to bucket"
        aws s3 sync ./upload s3://duckdb-featureserv
