on: [push, pull_request]

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: 'Install Go'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v5

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: 'Bundle Zip'
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main'
      env:
        MATRIX_OS: ${{ matrix.os }}
      run: ./ci/github-bundle.sh
      shell: bash

    - name: Upload Files to R2
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Uploading files to bucket"
        aws s3 sync ./upload s3://duckdb-featureserv --endpoint-url $AWS_ENDPOINT_URL
