on: [push, pull_request]
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: 'Install Go'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v5

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: 'Bundle Zip'
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main'
      env:
        MATRIX_OS: ${{ matrix.os }}
      run: ./ci/github-bundle.sh
      shell: bash

    - name: 'Login to AWS'
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: auto

    - name: 'Upload Zip'
      if: github.repository == 'tobilg/duckdb_featureserv' && github.ref_name == 'main'
      run: aws s3 sync ./upload s3://pg-featureserv
